use_frameworks!

platform :ios, '8.0'

target 'StartRateView_Example' do
  pod 'StartRateView', :path => '../'

  target 'StartRateView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
